name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1.8'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: sudo cp /var/www/.env /var/www/html/.env
    - name: Directory Permissions
      run: sudo chmod 777 /var/www/html/storage
